apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-repo
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: nephio-workload-repo
    repo: blueprints-nephio-gcp
    revision: main
  downstream:
    package: example-repo
    repo: config-control
  injectors:
  - kind: WorkloadCluster
    name: example
  - kind: ConfigMap
    name: gcp-context
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
