apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: example # kpt-set: ${name}
  namespace: config-control
spec:
  projectRef:
    external: example # kpt-set: ${project-id}
  location: global
  membershipRef:
    name: example # kpt-set: ${name}
  featureRef:
    name: example # kpt-set: ${name}
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        syncRepo: https://source.cloud.google.com/example/example # kpt-set: https://source.cloud.google.com/${project-id}/${name}
        syncBranch: main
        policyDir: /
        syncRev: HEAD
        secretType: none
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: example # kpt-set: ${name}
  namespace: config-control
spec:
  projectRef:
    external: example # kpt-set: ${project-id}
  location: global
  resourceID: configmanagement
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: example # kpt-set: ${project-id}
  name: example # kpt-set: ${name}
  namespace: config-control
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one.
    issuer: https://container.googleapis.com/v1/projects/example/locations/example/clusters/example # kpt-set: https://container.googleapis.com/v1/projects/${project-id}/locations/${location}/clusters/${name}
  endpoint:
    gkeCluster:
      resourceRef:
        name: example # kpt-set: ${name}
