apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: nephio-nodepool
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: example # kpt-set: ${project-id}
spec:
  location: example # kpt-set: ${zone}
  autoscaling:
    minNodeCount: 4
    maxNodeCount: 10
  clusterRef:
    name: example
