apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-values
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: gcp-context
    fieldPath: data.project-id
  targets:
  - select:
      kind: ConfigMap
      name: setters
    fieldPaths:
    - data.project-id
- source:
    kind: ConfigMap
    name: gcp-context
    fieldPath: data.location
  targets:
  - select:
      kind: ConfigMap
      name: setters
    fieldPaths:
    - data.location
