apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://source.developers.google.com/p/example/r/example # kpt-set: https://source.developers.google.com/p/${project-id}/r/${name}
    branch: main
    dir: /
    auth: gcpserviceaccount
    gcpServiceAccountEmail: nephio-config-sync@example.iam.gserviceaccount.com # kpt-set: nephio-config-sync@${project-id}.iam.gserviceaccount.com
